### PR TITLE
Add classifier for Spring boot 2 jar

### PR DESCRIPTION
**Pull request by mohshabbir**
fix for issue ##47

### CODE REVIEW

**Comment by MALPI** [comment]
Hi @mohshabbir. There is no need to integrate the spring boot plugin. What I actually meant in the issue is adding a classifier like `sb2` to the generated artifacts.

**Comment by MALPI** [comment]
Hey can you please give me an update if you are still working on it by Monday? Otherwise I'll close the PR and give others the chance to contribute.

**Comment by mohshabbir** [comment]
Hi @MALPI,

I've added a classifier to the artifact. If it's not what you wanted, you can close the PR and give others a chance to work on it. Thanks for giving a chance to work on it.

**Comment by MALPI** [comment]
Hi @mohshabbir, this is what I want but you are not using it at the right place. You have to add it as configuration to the [maven jar plugin](https://maven.apache.org/plugins/maven-jar-plugin/examples/attached-jar.html):
```
 <configuration>
              <classifier>sb2</classifier>
</configuration>
```
Looking forward for your change!

**Comment by MALPI** [comment]
I actually forgot to mention in the issue description. You should use `zalando-incubator:feature/spring-boot-2` as base and also file your PR against this branch.

**Pull request closed without merging**
