### PR TITLE
Feature/spring boot 2 create example module

### LINKED ISSUE #54: Port the sample application to Spring Boot 2
Port the sample application that was created in #49 to the SB 2 feature branch. This will also update the feature branch structure to the Maven multi-module structure.

### PR DESCRIPTION
**Pull request by robvanderleek**
Fixes #54 
A port of the sample application to the spring-boot-2 feature branch.

Could the label 'hacktoberfest' be added to this issue? (since my contribution is in the spirit of Hacktoberfest 2017).

### CODE REVIEW

**Comment by MALPI** [comment]
Hi @robvanderleek thanks for your PR once more and sorry for the late response! In order to keep the amount of changed files as low as possible, I think we should first file a PR to merge changes from Master and another one for changes which are needed to create the port. What do you think?

**Comment by robvanderleek** [comment]
Hi @MALPI, the current PR is quite bloated so I agree of splitting it up. I'm not exactly sure how to proper split it though. There are some changes to master before I restructured the codebase, then the restructuring, then some merges and more of my changes for the sample example and finally the port to SB2. Those last changes are needed to get the port working with SB2. Do you have a suggestion how to break up the PR?

**Comment by MALPI** [comment]
I guess you created your branch from Master as base? Not sure, but probably we cannot simply merge master to this branch. But apply the changes step by step. Would need to check in detail in the next days.

**Comment by robvanderleek** [comment]
IIRC I used `feature/spring-boot-2` as a base for this branch. Then merged in master and made changes to get the sample app working with SB2. It's no problem for me to redo the branch, let me know what sequence of steps you would prefer.

**Comment by MALPI** [comment]
Ok, going to review tonight probably.

**Comment by MALPI** [comment]
:+1:

**Comment by MALPI** [comment]
@mmodabber @coders-kitchen please review/approve

**Comment by coders-kitchen** [comment]
👍

**Pull request merged**
